# Generated by Django 4.0.3 on 2022-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creatingproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT_TITLE', models.CharField(max_length=255, unique=True)),
                ('DESCRIPTION', models.TextField(blank=True, max_length=500)),
                ('IS_ACTIVE', models.BooleanField(blank=True, null=True)),
                ('DATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='las_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT', models.TextField(max_length=255)),
                ('TASK', models.TextField(blank=True, max_length=100)),
                ('POTREE_HTML_FILE', models.TextField(blank=True, max_length=255)),
                ('IS_ACTIVE', models.BooleanField(blank=True)),
                ('IS_CONVERTED', models.BooleanField(blank=True)),
                ('DATE', models.DateTimeField(auto_now=True)),
                ('FILE', models.FileField(upload_to='media')),
            ],
        ),
    ]
