# Generated by Django 4.0.3 on 2022-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiderapp', '0002_creatingproject_project_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatingproject',
            name='PROJECT_UPDATED_DATE',
        ),
        migrations.RemoveField(
            model_name='las_files',
            name='TASK_UPDATED_DATE',
        ),
        migrations.AddField(
            model_name='las_files',
            name='POTREE_PUBLIC_HTML_FILE',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
