# Generated by Django 4.0.3 on 2022-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiderapp', '0003_remove_creatingproject_project_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=100, unique=True)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.TextField(max_length=1000)),
                ('ROLE', models.CharField(max_length=50)),
            ],
        ),
    ]
